spring:
    r2dbc:
        url: ${SPRING_DATASOURCE_URL:r2dbc:postgresql://localhost:5432/test-sync}
        username: ${SPRING_DATASOURCE_USERNAME:postgres}
        password: ${SPRING_DATASOURCE_PASSWORD:root}
        properties:
            schema: test-sync